basePath: /v1
definitions:
  models.Companies:
    properties:
      created_at:
        type: string
      currency_name:
        type: string
      description:
        type: string
      homepage_url:
        type: string
      id:
        type: string
      locale:
        type: string
      logo_url:
        type: string
      market:
        type: string
      name:
        type: string
      primary_exchange:
        type: string
      ticker:
        type: string
      total_employees:
        type: number
      type:
        type: string
      updated_at:
        type: string
    type: object
  models.CompanyStock:
    properties:
      close_price:
        type: number
      created_at:
        type: string
      date:
        type: string
      highest_price:
        type: number
      id:
        type: string
      lowest_price:
        type: number
      number_of_transactions:
        type: integer
      open_price:
        type: number
      otc:
        type: boolean
      ticker:
        type: string
      trading_volume:
        type: integer
      updated_at:
        type: string
      volume_weighted_average_price:
        type: number
    type: object
  models.UserAssets:
    properties:
      company_stock_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      price_per_unit:
        type: number
      quantity:
        type: integer
      ticker:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.UserTransactions:
    properties:
      buy_price:
        type: number
      company_stock_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      quantity:
        type: integer
      sell_price:
        type: number
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  v1Companies.GetCompanyInfoResponse:
    properties:
      company:
        $ref: '#/definitions/models.Companies'
      company_stock:
        $ref: '#/definitions/models.CompanyStock'
    type: object
  v1Users.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  v1Users.UserRegistrationRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  v1Users.UserRegistrationResponse:
    properties:
      current_balance:
        type: number
      email:
        type: string
      starting_balance:
        type: number
      username:
        type: string
    type: object
  v1companystock.BuyCompanyStockRequest:
    properties:
      company_stock_id:
        type: string
      quantity:
        type: integer
    type: object
  v1companystock.BuyOrSellCompanyStocksRequest:
    properties:
      buy_or_sell:
        type: string
      company_stock_id:
        type: string
      quantity:
        type: integer
    type: object
  v1companystock.SellCompanyStockRequest:
    properties:
      company_stock_id:
        type: string
      quantity:
        type: integer
    type: object
  v1userassets.UserAssetsProfits:
    properties:
      company_stock:
        items:
          $ref: '#/definitions/v1userassets.UserAssetsProfitsPerStock'
        type: array
      total_current_value:
        type: number
      total_profit_:
        type: number
      total_profit_margin:
        type: string
      total_spent:
        type: number
    type: object
  v1userassets.UserAssetsProfitsPerStock:
    properties:
      buy_price:
        type: number
      company_stock:
        $ref: '#/definitions/models.CompanyStock'
      current_price:
        type: number
      profit_margin:
        type: string
      profit_per_unit:
        type: number
      quantity:
        type: integer
      total_buy_price:
        type: number
      total_current_price:
        type: number
      total_profit:
        type: number
    type: object
  v1userassets.UserAssetsValues:
    properties:
      quantity:
        type: integer
      ticker:
        type: string
      value:
        type: number
      value_per_unit:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Capital-Challenge backend API.
  title: Capital-Challenge API
  version: "1.0"
paths:
  /companies/{ticker}:
    get:
      consumes:
      - application/json
      description: get company info by Ticker
      parameters:
      - description: Ticker
        in: path
        name: ticker
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1Companies.GetCompanyInfoResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get Company info
      tags:
      - companies
  /company-stocks:
    get:
      description: get the daily information about company stocks
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get Daily Company Stock
      tags:
      - company_stock
  /company-stocks/{user_id}:
    post:
      description: buy or sell the selected amount of company stock
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1companystock.BuyOrSellCompanyStocksRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserTransactions'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: BuyOrSellCompanyStock
      tags:
      - company_stock
  /company-stocks/buy/{user_id}:
    post:
      description: buy the selected amount of company stock
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1companystock.BuyCompanyStockRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserTransactions'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: BuyCompanyStock
      tags:
      - company_stock
  /company-stocks/sell/{user_id}:
    post:
      description: sell the selected amount of company stock
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1companystock.SellCompanyStockRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserTransactions'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: SellCompanyStock
      tags:
      - company_stock
  /user-assets/{user_id}:
    get:
      description: get user assets for current game
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserAssets'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: GetUserAssets
      tags:
      - user_assets
  /user-assets/profits/{user_id}:
    get:
      description: get user assets profits
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1userassets.UserAssetsProfits'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: GetUserAssetsProfits
      tags:
      - user_assets
  /user-assets/value/{user_id}:
    get:
      description: get user assets values
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1userassets.UserAssetsValues'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: GetUserAssetsValue
      tags:
      - user_assets
  /users/:
    post:
      description: Login user
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1Users.UserLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Login user
      tags:
      - users
  /users/register:
    post:
      description: Register user
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1Users.UserRegistrationRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1Users.UserRegistrationResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Register user
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
